name: docker-build-and-push.yml

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        IMAGE_NAME:
          [
            "telegraf-with-extras"
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get Changed Files
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: ${{ matrix.IMAGE_NAME }}

      - name: Set up QEMU
        if: steps.changed.outputs.changed == 'true'
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        if: steps.changed.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: steps.changed.outputs.changed == 'true'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        if: steps.changed.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.IMAGE_NAME }}/
          platforms: linux/amd64
          push: true
          # tag /w a branch if it's a thing?
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.IMAGE_NAME }}:latest